name: UPM

on:
  push:
    branches: [main]

jobs:
  split-upm:
    permissions:
      contents: write
    name: Update UPM branches (latest git)
    runs-on: ubuntu-latest
    env:
      EVH_CORE_PKG_ROOT: Packages/il.runiarl.eventhorizon
      EVH_METAXR_PKG_ROOT: Packages/il.runiarl.eventhorizon.metaxr
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: update branch `upm` (core package)
        run: |
          git subtree split -P "$EVH_CORE_PKG_ROOT" -b upm
          git push -u origin upm -f
      - name: update branch `upm-metaxr` (metaxr support)
        run: |
            git subtree split -P "$EVH_METAXR_PKG_ROOT" -b upm-metaxr
            git push -u origin upm-metaxr -f