name: UPM branch

on:
  push:
    branches: [main]

jobs:
  split-upm:
    name: Update UPM branches (latest git)
    runs-on: ubuntu-latest
    env:
      PKG_ROOT: Packages/ac.arl.eventhorizon
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: update upm branch
        run: |
          git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}
          git subtree split -P "$PKG_ROOT" -b upm
          git push -u origin upm