name: UPM

on:
  push:
    branches: [main]

jobs:
  split-upm:
    permissions:
      contents: write
    name: Update UPM branches (latest git)
    runs-on: ubuntu-latest
    env:
      PKG_ROOT: Packages/il.runiarl.eventhorizon
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: update upm branch
        run: |
          git subtree split -P "$PKG_ROOT" -b upm
          git push -u origin upm -f